apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: supermario
  name: supermario
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: supermario
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: supermario
    spec:
      containers:
      - image: pengbai/docker-supermario
        imagePullPolicy: Always
        name: docker-supermario
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
